### PR TITLE
Auto detect string encoding used by Libpcap

### LINKED ISSUE #300: Non ASCII chars on path \ file name causing exception
Hi! 

I came across this exception when trying to read a file that contains non ASCII chars at his name:  
**"Unable to open offline adapter: <THE-FILE-PATH>: Invalid argument"**
The non ASCII chars are shown as question marks (picture attached) even though the file exists (the original file name is: "Non ASCII file name - (אבג).pcap"). 
image

Thank you for the efforts invested in the development of this package!

 Oded.

### PR DESCRIPTION
**Pull request by kayoub5**
Fixes #300

### CODE REVIEW

**Comment by kayoub5** [comment]
@chmorgan failed test have nothing to do with strings, could you force re-run it?

**Comment by chmorgan** [comment]
Wow, this is way way more extensive than I would have thought.

**Review by chmorgan — CHANGES_REQUESTED** [review]
Reviewed and it looks good to me. Can you update the copyrights on the new file(s) you added with your info? You might also fixup the first commit with the last commit since it looks like the last commit basically fixes the first commit?

File: Test/Statistics/StatisticsDeviceTest.cs [hunk 1]
```diff
@@ -61,6 +61,7 @@ public void Test()
 
             var count = 7;
 
+            Thread.Sleep(100);
```
Comment (kayoub5) [inline Test/Statistics/StatisticsDeviceTest.cs:64]: This change was put in its own commit since it had no relation with actual PR content, but was needed for CI to pass

**Review by chmorgan — APPROVED** [review]
