### PR TITLE
Use SafeHandle

### LINKED ISSUE #295: AccessViolationException on MarshalRawPacket
Runtime system: Windows (client installation so not much known and unable to reproduce on developer machine)
Installed software: SharpPcap 5.4.0
Application uses .NET Version 4.8

We came across several of our customers running different windows environments, having the following issue that is being logged in our software. Seems like memory access issue with pointers but I'm not and expert. Even though it looks like a duplicate of https://github.com/chmorgan/sharppcap/issues/290, the originating code where it occurs is quite different. Note that I was not able to reproduce as it works for 99,99% of the cases. Any clue as to what could be going wrong?

Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
at System.Runtime.InteropServices.Marshal.CopyToManaged(IntPtr, System.Object, Int32, Int32)
at SharpPcap.LibPcap.PcapDevice.MarshalRawPacket(IntPtr, IntPtr)
at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr, IntPtr, IntPtr)
at SharpPcap.LibPcap.Windows.pcap_dispatch(IntPtr, Int32, pcap_handler, IntPtr)
at SharpPcap.LibPcap.PcapDevice.CaptureThread(System.Threading.CancellationToken)
at SharpPcap.LibPcap.PcapDevice+<>c_DisplayClass79_0.<StartCapture>b_0()

### PR DESCRIPTION
**Pull request by kayoub5**
Fixes #295
Same tests that crash in #305 are now passing here.

@KoenPlasmansLS could you test if this PR fixes your problem?

Other handles needs to be updated as well from `IntPtr` to `SafeHandle`, those should be addressed in other PRs otherwise this PR would be too big.

List of handles that needs updating (in the future)
* `pcap_dumper_t *`
* `bpf_program *`
* `pcap_pkthdr *`
* `pcap_stat *`
* `pcap_if_t *`
* `int **tstamp_typesp`

### CODE REVIEW

**Comment by kayoub5** [comment]
@chmorgan could you enable "Rolling builds" in Appveyor, so that newer commits cancel obsolete ones

**Comment by chmorgan** [comment]
@kayoub5 should we enable rolling builds in .appveyor.yml? I see the option in the gui but wondered if that was something the .yml should handle. It feels like it isn't a branch or fork specific thing though so not sure how it works if its in yml.

**Comment by kayoub5** [comment]
> @kayoub5 should we enable rolling builds in .appveyor.yml? I see the option in the gui but wondered if that was something the .yml should handle. It feels like it isn't a branch or fork specific thing though so not sure how it works if its in yml.

Rolling builds can only be enabled from gui.

**Comment by kayoub5** [comment]
@chmorgan review?

**Comment by chmorgan** [comment]
@kayoub5 rolling builds enabled

File: SharpPcap/LibPcap/PcapHandle.cs [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+SharpPcap is distributed in the hope that it will be useful,
+but WITHOUT ANY WARRANTY; without even the implied warranty of
+MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+GNU Lesser General Public License for more details.
+
+You should have received a copy of the GNU Lesser General Public License
+along with SharpPcap.  If not, see <http://www.gnu.org/licenses/>.
+*/
+/*
+ * Copyright 2010 Chris Morgan <chmorgan@gmail.com>
```
Comment (chmorgan) [inline SharpPcap/LibPcap/PcapHandle.cs:18]: can you update this with your info?

**Review by chmorgan — COMMENTED** [review]
Approved with that copyright update. It was a lot of lines of change that I was surprised to see were relatively easy to follow. SafeHandle is new to me so I'm going with your experience here, looks like the right thing to do based on some SO I've found about SafeHandle usage.

**Comment by kayoub5** [comment]
@chmorgan could you publish a new nuget version with the PRs merged so far?

**Comment by mitch842** [comment]
Hey @kayoub5 @chmorgan, any update on publishing a new nuget?

**Comment by chmorgan** [comment]
6.1.0 with a ton of improvements by @kayoub5 should be live on nuget now!
